/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Larissa
 */
public class ListObject extends javax.swing.JPanel {

    /**
     * Creates new form ListObject
     */
    public ListObject() {
        initComponents();
    }
    
    public ListObject(String name) {
        initComponents();
        listObjectName.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listObjectName = new javax.swing.JLabel();
        listObjectImage = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(155, 40));
        setMinimumSize(new java.awt.Dimension(155, 40));
        setPreferredSize(new java.awt.Dimension(155, 40));

        listObjectName.setText("Untitled");

        listObjectImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fileUntitled.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(listObjectName)
                .addGap(18, 18, 18)
                .addComponent(listObjectImage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listObjectName)
                    .addComponent(listObjectImage, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel listObjectImage;
    private javax.swing.JLabel listObjectName;
    // End of variables declaration//GEN-END:variables
}
