
package view;

import javax.swing.JLabel;
import javax.swing.JTextPane;

import model.TextLineNumber;

/**
 *
 * @author Larissa
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    
    public JLabel getRegua() {
        return this.regua;
    }
    
    public JTextPane getPainelTexto() {
        return this.painelDeTexto;
    }
    
    public String getPath(){
    	return this.path;
    }
    
    public void setPath(String path){
    	this.path = path;
    }
    
    public Boolean getExist(){
    	return this.exist;
    }
    
    public void setExist(Boolean exist){
    	this.exist = exist;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	path = new String();
    	exist = false;
        mainPaneAuxiliar = new javax.swing.JPanel();
        regua = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelDeTexto = new javax.swing.JTextPane();

        regua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/rulerBar.png"))); // NOI18N

        painelDeTexto.setBorder(null);
        TextLineNumber tln = new TextLineNumber(painelDeTexto);
        jScrollPane1.setRowHeaderView( tln );
        painelDeTexto.setPreferredSize(new java.awt.Dimension(785, 20));
        jScrollPane1.setViewportView(painelDeTexto);

        javax.swing.GroupLayout mainPaneAuxiliarLayout = new javax.swing.GroupLayout(mainPaneAuxiliar);
        mainPaneAuxiliar.setLayout(mainPaneAuxiliarLayout);
        mainPaneAuxiliarLayout.setHorizontalGroup(
            mainPaneAuxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPaneAuxiliarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPaneAuxiliarLayout.setVerticalGroup(
            mainPaneAuxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneAuxiliarLayout.createSequentialGroup()
                .addComponent(regua, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPaneAuxiliar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPaneAuxiliar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPaneAuxiliar;
    private javax.swing.JTextPane painelDeTexto;
    private javax.swing.JLabel regua;
    private String path;
    private Boolean exist;
    // End of variables declaration//GEN-END:variables
}
